name = 'Simple Hugo Theme'
license = 'MIT NON-AI'
licenselink = 'https://github.com/saaste/simple-hugo-theme/LICENSE'
description = 'Super Simple Hugo Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/saaste/simple-hugo-theme'

# If the theme has a single author
[author]
  name = 'saaste'
  homepage = 'https://saaste.net'